### ISSUE TITLE
RGB: Frontend

### ISSUE THREAD

**Issue by CalrethilOfMirkwood** [CalrethilOfMirkwood/flask_portfolio#14]
Do the frontend of the RGB project.  Figure out how to change an image to grey scale dynamically (look for the Hack in code).

**Comment by FierceExplorer** [comment]
I will be helping Jason with that.

**Comment by strangiato2112** [comment]
I have been able to figure out how to make the grayscale image appear no i just need to figure out how to toggle them back and forth

**Comment by strangiato2112** [comment]
I finally managed to get the frontend and the grayscale toggle to work with one button and it switches all the images to grayscale

**Comment by strangiato2112** [comment]
commit ae3de46
commit 367f852
